export const curatedAlbums = [
  { title: "Thriller", artist: "Michael Jackson" },
  { title: "Off the Wall", artist: "Michael Jackson" },
  { title: "Bad", artist: "Michael Jackson" },
  { title: "The Dark Side of the Moon", artist: "Pink Floyd" },
  { title: "The Wall", artist: "Pink Floyd" },
  { title: "Abbey Road", artist: "The Beatles" },
  { title: "Nevermind", artist: "Nirvana" },
  { title: "Back in Black", artist: "AC/DC" },
  { title: "Rumours", artist: "Fleetwood Mac" },
  { title: "OK Computer", artist: "Radiohead" },
  { title: "Kid A", artist: "Radiohead" },
  { title: "In Rainbows", artist: "Radiohead" },
  { title: "Purple Rain", artist: "Prince" },
  { title: "1999", artist: "Prince" },
  { title: "Sign o' the Times", artist: "Prince" },
  { title: "Born in the U.S.A.", artist: "Bruce Springsteen" },
  { title: "Hotel California", artist: "Eagles" },
  { title: "Appetite for Destruction", artist: "Guns N' Roses" },
  { title: "Like a Prayer", artist: "Madonna" },
  { title: "Kind of Blue", artist: "Miles Davis" },
  { title: "Songs in the Key of Life", artist: "Stevie Wonder" },
  { title: "Innervisions", artist: "Stevie Wonder" },
  { title: "Blue", artist: "Joni Mitchell" },
  { title: "What's Going On", artist: "Marvin Gaye" },
  { title: "Pet Sounds", artist: "The Beach Boys" },
  { title: "Exile on Main St.", artist: "The Rolling Stones" },
  { title: "Led Zeppelin IV", artist: "Led Zeppelin" },
  { title: "Are You Experienced", artist: "Jimi Hendrix" },
  { title: "The Chronic", artist: "Dr. Dre" },
  { title: "Illmatic", artist: "Nas" },
  { title: "The Miseducation of Lauryn Hill", artist: "Lauryn Hill" },
  { title: "Ready to Die", artist: "The Notorious B.I.G." },
  { title: "The Marshall Mathers LP", artist: "Eminem" },
  { title: "21", artist: "Adele" },
  { title: "25", artist: "Adele" },
  { title: "Random Access Memories", artist: "Daft Punk" },
  { title: "Discovery", artist: "Daft Punk" },
  { title: "Lemonade", artist: "Beyoncé" },
  { title: "Blonde", artist: "Frank Ocean" },
  { title: "Channel Orange", artist: "Frank Ocean" },
  { title: "To Pimp a Butterfly", artist: "Kendrick Lamar" },
  { title: "DAMN.", artist: "Kendrick Lamar" },
  { title: "Currents", artist: "Tame Impala" },
  { title: "AM", artist: "Arctic Monkeys" },
  { title: "Funeral", artist: "Arcade Fire" },
  { title: "Is This It", artist: "The Strokes" },
  { title: "American Idiot", artist: "Green Day" },
  { title: "Dookie", artist: "Green Day" },
  { title: "Elephant", artist: "The White Stripes" },
  { title: "1989", artist: "Taylor Swift" },
  { title: "Folklore", artist: "Taylor Swift" },
  { title: "Future Nostalgia", artist: "Dua Lipa" },
  { title: "After Hours", artist: "The Weeknd" },
  { title: "Scorpion", artist: "Drake" },
  { title: "Take Care", artist: "Drake" },
  { title: "Voodoo", artist: "D'Angelo" },
  { title: "Loveless", artist: "My Bloody Valentine" },
  { title: "Doolittle", artist: "Pixies" },
  { title: "Definitely Maybe", artist: "Oasis" },
  { title: "(What's the Story) Morning Glory?", artist: "Oasis" },
  { title: "Grace", artist: "Jeff Buckley" },
  { title: "Tapestry", artist: "Carole King" },
  { title: "Legend", artist: "Bob Marley & The Wailers" },
  { title: "Hunky Dory", artist: "David Bowie" },
  { title: "The Rise and Fall of Ziggy Stardust and the Spiders from Mars", artist: "David Bowie" },
  { title: "London Calling", artist: "The Clash" },
  { title: "Never Mind the Bollocks Here's the Sex Pistols", artist: "Sex Pistols" },
  { title: "Ten", artist: "Pearl Jam" },
];
